language: node_js
node_js:
  - 12

cache:
  directories:
    - $TRAVIS_BUILD_DIR/demo/node_modules
    - $TRAVIS_BUILD_DIR/demo/functions/node_modules

before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/demo
  - cp -R packages/rmw-shell/cra-template-rmw/template $TRAVIS_BUILD_DIR/demo
  - cd $TRAVIS_BUILD_DIR/demo
  - chmod +x $TRAVIS_BUILD_DIR/demo/continuous_deployment/before_install.sh
  - $TRAVIS_BUILD_DIR/demo/continuous_deployment/before_install.sh

before_script:
  - npm test
  - chmod +x ./continuous_deployment/build.sh
  - travis_wait 40 ./continuous_deployment/build.sh

script:
  - chmod +x ./continuous_deployment/deploy.sh
  - travis_wait 40 ./continuous_deployment/deploy.sh
