language: node_js
node_js:
  - 8

cache:
  directories:
    - packages/rmw-shell/cra-template-rmw/template/node_modules
    - packages/rmw-shell/cra-template-rmw/template/functions/node_modules

before_install:
  - cd packages/rmw-shell/cra-template-rmw/template
  - chmod +x ./continuous_deployment/before_install.sh
  - ./continuous_deployment/before_install.sh

before_script:
  - npm test
  - chmod +x ./continuous_deployment/build.sh
  - travis_wait 40 ./continuous_deployment/build.sh

script:
  - chmod +x ./continuous_deployment/deploy.sh
  - travis_wait 40 ./continuous_deployment/deploy.sh
