language: node_js
node_js:
  - 12

cache:
  directories:
    - $TRAVIS_BUILD_DIR/demo/node_modules
    - $TRAVIS_BUILD_DIR/demo/functions/node_modules

before_install:
  - mkdir -p demo/
  - cp -R packages/rmw-shell/cra-template-rmw/template demo/
  - cd demo/continuous_deployment
  - chmod +x before_install.sh
  - ./before_install.sh

before_script:
  - npm test
  - chmod +x ./continuous_deployment/build.sh
  - travis_wait 40 ./continuous_deployment/build.sh

script:
  - chmod +x ./continuous_deployment/deploy.sh
  - travis_wait 40 ./continuous_deployment/deploy.sh
