language: node_js
node_js:
  - 12

cache:
  directories:

before_install:
  - npx create-react-app demo --template rmw
  - cd demo
  - chmod +x ./continuous_deployment/before_install.sh
  - ./continuous_deployment/before_install.sh

before_script:
  - npm test
  - chmod +x ./continuous_deployment/build.sh
  - travis_wait 40 ./continuous_deployment/build.sh

script:
  - chmod +x ./continuous_deployment/deploy.sh
  - travis_wait 40 ./continuous_deployment/deploy.sh
