language: node_js
node_js:
  - 6
cache:
  directories:
  - node_modules

before_install:
  - npm install -g firebase-tools
  - npm install codecov.io coveralls
  - cd functions
  - npm install
  - cd ..

script:
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run build
  - firebase use default --token $FIREBASE_TOKEN
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN

branches:
  only:
    - master
